### ISSUE TITLE
Member List Hatası [Bug]

### ISSUE THREAD

**Issue by AhmetAksunger** [ismkdc/DiscordClone#1]
Sağ üstte bulunan "Member List" ikonuna bir kez tıklayınca olması gerektiği gibi kullanıcı listesi kapanıyor. Fakat tekrar basıldığında beyaz bir sayfa çıkıyor. Gözden kaçmış sanırım.
![Screenshot_18](https://user-images.githubusercontent.com/116587797/232876493-52dc42b2-4760-4d0d-9153-3661e01d6540.png)

**Comment by ismkdc** [comment]
selamlar,
geri bildirim için teşekkür ederim.
frontend tarafını farklı bir repodan klonlandığım için ordan gelmiş bir bug olmalı :)
projeyi aslında bir backend demosu olarak planlamıştım fakat görsel bişeylerde olsun diye arkadaşın yapmış olduğu template'i kullandım o yüzden büyük ihtimalle fixlemeye zaman ayıramacağım.
